return {
  PLAYER = {
    FRICTION = 1.5,
    MAX_SPEED = 360,
    SIZE = 64,
    MAX_CHARGE = 2
  },
  SPAWNER = {
    SPAWN_OFFSCREEN_OFFSET = 50,
    INITIAL_SPAWN_INTERVAL = 1.5, -- every 1 second
    BASE_MAX_OBSTACLE_VELOCITY = 25,
    BASE_MIN_OBSTACLE_VELOCITY = 10
  },
  SCORE = {
    START = 0,
    INCREMENT = 10,
    X = 10,
    Y = 10
  },
  REMOVE_OBSTACLES_BUFFER_DISTANCE = 100, -- this MUST be greater than SPAWN_OFFSCREEN_OFFSET
  CHARGE_BAR_HEIGHT = 0.04,
  CHARGE_BAR_WIDTH = 0.6
}
